---
all:
  children:
    web:
      hosts:
        vps:
          ansible_host: "{{ vps_ansible_host }}"
          ansible_user: "{{ vps_ansible_user }}"
          ansible_port: "{{ vps_ansible_port }}"
          ansible_ssh_private_key_file: "{{ vps_ansible_ssh_private_key_file }}"